# Generated by Django 6.0.1 on 2026-06-11 17:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='registry.faculty')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('faculty', 'code'), ('faculty', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IssuanceBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(help_text='Calendar year this batch belongs to, for archival/reporting grouping.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CONFIRMATION_OPEN', 'Confirmation Open'), ('CONFIRMATION_CLOSED', 'Confirmation Closed'), ('ISSUANCE_IN_PROGRESS', 'Issuance In Progress'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30)),
                ('confirmation_deadline', models.DateTimeField()),
                ('confirmation_opens_at', models.DateTimeField(blank=True, help_text='Optional delayed open. If null, confirmation opens at publish.', null=True)),
                ('confirmation_deadline_original', models.DateTimeField(blank=True, help_text='Original confirmation deadline at creation. Never updated after first extension.', null=True)),
                ('confirmation_deadline_extended_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_deadline_extension_count', models.PositiveSmallIntegerField(default=0)),
                ('issuance_instructions', models.TextField(blank=True, help_text='Per-batch message included in the issuance notification email.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_closed_at', models.DateTimeField(blank=True, null=True)),
                ('issuance_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('certificate_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuance_batches', to='templates.certificatetemplate')),
                ('confirmation_deadline_extended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extended_batch_deadlines', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=512)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_ERRORS', 'Completed With Errors'), ('FAILED', 'Failed')], default='PROCESSING', max_length=30)),
                ('error_log', models.JSONField(blank=True, default=list, help_text='List of {row, field, message} dicts.')),
                ('email_summary', models.JSONField(blank=True, default=dict, help_text='{sent, failed, pending} counts captured post-publish.')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='registry.issuancebatch')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DeadlineExtensionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_deadline', models.DateTimeField()),
                ('new_deadline', models.DateTimeField()),
                ('extended_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('extended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadline_extension_logs', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_extensions', to='registry.issuancebatch')),
            ],
            options={
                'ordering': ['-extended_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchStatusTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='registry.issuancebatch')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IssuanceRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('filter_criteria', models.JSONField(blank=True, default=dict)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('total_targeted', models.PositiveIntegerField(default=0)),
                ('succeeded_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuance_runs', to='registry.issuancebatch')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuance_runs_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('institutional_email', models.EmailField(max_length=254)),
                ('programme', models.CharField(max_length=255)),
                ('class_of_degree', models.CharField(max_length=80)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('date_of_completion', models.DateField()),
                ('extra_fields', models.JSONField(blank=True, default=dict, help_text='Template-specific fields keyed by name.')),
                ('confirmation_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FLAGGED', 'Flagged'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20)),
                ('confirmation_token_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 of the plaintext token sent in the email.', max_length=128)),
                ('confirmation_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_email_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], default='PENDING', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dispute_note', models.TextField(blank=True)),
                ('dispute_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_resolution_note', models.TextField(blank=True)),
                ('issuance_status', models.CharField(choices=[('NOT_ISSUED', 'Not Issued'), ('QUEUED', 'Queued'), ('ISSUED', 'Issued'), ('FAILED', 'Failed')], default='NOT_ISSUED', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('issuance_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='registry.issuancebatch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_records', to='registry.department')),
                ('dispute_resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_records', to='registry.faculty')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_records', to='registry.importbatch')),
                ('last_issuance_run', models.ForeignKey(blank=True, help_text='Most recent issuance run this record was included in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='registry.issuancerun')),
            ],
            options={
                'ordering': ['index_number'],
            },
        ),
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_type', models.CharField(choices=[('CONFIRMATION', 'Confirmation URL'), ('CONFIRMATION_ACK', 'Confirmation acknowledgement'), ('DISPUTE_ACK', 'Dispute acknowledgement'), ('RECORD_CORRECTED', 'Record corrected re-confirmation'), ('DISPUTE_REJECTED', 'Dispute resolved without correction'), ('ISSUANCE', 'Certificate issued notification')], max_length=30)),
                ('recipient', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('BOUNCED', 'Bounced'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='registry.issuancebatch')),
                ('student_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='registry.studentrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmationAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('TOKEN_GENERATED', 'Token generated'), ('EMAIL_SENT', 'Confirmation email sent'), ('EMAIL_FAILED', 'Confirmation email delivery failed'), ('PAGE_VIEWED', 'Confirmation page viewed'), ('CONFIRMED', 'Confirmation submitted'), ('DISPUTED', 'Dispute submitted'), ('TOKEN_EXPIRED', 'Token expired'), ('RESEND_REQUESTED', 'Resend requested'), ('VALIDATION_FAILED', 'Token/index validation failed'), ('ANOMALOUS_IP', 'Anomalous IP flagged')], max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='registry.issuancebatch')),
                ('student_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='registry.studentrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='issuancebatch',
            index=models.Index(fields=['status'], name='registry_is_status_0dbd84_idx'),
        ),
        migrations.AddIndex(
            model_name='issuancebatch',
            index=models.Index(fields=['year'], name='registry_is_year_3aaaf0_idx'),
        ),
        migrations.AddIndex(
            model_name='deadlineextensionlog',
            index=models.Index(fields=['batch', '-extended_at'], name='registry_de_batch_i_401a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='issuancerun',
            index=models.Index(fields=['batch', '-created_at'], name='registry_is_batch_i_fcb8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='issuancerun',
            index=models.Index(fields=['status'], name='registry_is_status_05bf8f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrecord',
            index=models.Index(fields=['batch', 'confirmation_status'], name='registry_st_batch_i_33450b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrecord',
            index=models.Index(fields=['batch', 'issuance_status'], name='registry_st_batch_i_5781a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentrecord',
            unique_together={('batch', 'index_number')},
        ),
        migrations.AddIndex(
            model_name='emaildeliverylog',
            index=models.Index(fields=['batch', 'email_type', 'status'], name='registry_em_batch_i_3326c1_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildeliverylog',
            index=models.Index(fields=['student_record', 'email_type'], name='registry_em_student_555ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='confirmationauditlog',
            index=models.Index(fields=['batch', 'event_type'], name='registry_co_batch_i_2b99b1_idx'),
        ),
        migrations.AddIndex(
            model_name='confirmationauditlog',
            index=models.Index(fields=['student_record', 'timestamp'], name='registry_co_student_c65643_idx'),
        ),
    ]
