# Generated by Django 6.0.1 on 2026-06-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuancebatch',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Calendar year this batch belongs to, for archival/reporting grouping. Auto-populated from confirmation_deadline if omitted.'),
        ),
    ]
