# Generated by Django 6.0.1 on 2026-06-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_issuancebatch_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='mapping_configuration',
            field=models.JSONField(blank=True, help_text='Column-to-field mapping used for this import.', null=True),
        ),
    ]
