# Generated by Django 6.0.1 on 2026-06-17 14:33

from django.db import migrations, models


def _heuristic_parse_name(full_name):
    """Best-effort split: first word = first_name, last word = last_name, middle = other_names."""
    if not full_name:
        return '', '', ''
    parts = full_name.strip().split()
    if len(parts) == 1:
        return parts[0], '', ''
    if len(parts) == 2:
        return parts[0], '', parts[1]
    return parts[0], ' '.join(parts[1:-1]), parts[-1]


def backfill_name_components(apps, schema_editor):
    StudentRecord = apps.get_model('registry', 'StudentRecord')
    for record in StudentRecord.objects.filter(first_name=''):
        first, other, last = _heuristic_parse_name(record.full_name)
        record.first_name = first
        record.other_names = other
        record.last_name = last
        record.name_order = ['first_name', 'other_names', 'last_name']
        record.save(update_fields=['first_name', 'other_names', 'last_name', 'name_order', 'full_name'])


def reverse_backfill(apps, schema_editor):
    pass  # No-op; forward migration is lossy anyway.


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_add_mapping_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='name_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='other_names',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(backfill_name_components, reverse_backfill),
    ]
