# Generated by Django 6.0.1 on 2026-05-26 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_finalize_congregation_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineExtensionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_deadline', models.DateTimeField()),
                ('new_deadline', models.DateTimeField()),
                ('extended_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deadline_extensions', to='registry.congregation')),
                ('extended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadline_extension_logs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_extensions', to='registry.congregationsession')),
            ],
            options={
                'ordering': ['-extended_at'],
                'indexes': [models.Index(fields=['session', '-extended_at'], name='registry_de_session_ce1910_idx'), models.Index(fields=['congregation', '-extended_at'], name='registry_de_congreg_6f65ce_idx')],
            },
        ),
    ]
