# Generated by Django 6.0.1 on 2026-06-19 10:42

from django.db import migrations, models


def backfill_reference_names(apps, schema_editor):
    """Assign BATCH-{year}-{NNNN} to existing batches, deterministic by year + created_at."""
    IssuanceBatch = apps.get_model('registry', 'IssuanceBatch')
    seq_by_year = {}
    qs = IssuanceBatch.objects.all().order_by('year', 'created_at', 'id')
    for batch in qs:
        if batch.reference_name:
            continue
        year = batch.year or (batch.created_at.year if batch.created_at else 0)
        seq_by_year[year] = seq_by_year.get(year, 0) + 1
        batch.reference_name = f'BATCH-{year}-{seq_by_year[year]:04d}'
        batch.save(update_fields=['reference_name'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_add_original_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuancebatch',
            name='reference_name',
            field=models.CharField(blank=True, default='', help_text='Human-friendly reference, auto-generated as BATCH-{year}-{NNNN}.', max_length=32),
        ),
        migrations.RunPython(backfill_reference_names, noop_reverse),
        migrations.AlterField(
            model_name='issuancebatch',
            name='reference_name',
            field=models.CharField(blank=True, help_text='Human-friendly reference, auto-generated as BATCH-{year}-{NNNN}.', max_length=32, unique=True),
        ),
    ]
