# Generated by Django 6.0.1 on 2026-05-26 12:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_deadline_extension_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuanceBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('filter_criteria', models.JSONField(blank=True, default=dict)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('total_targeted', models.PositiveIntegerField(default=0)),
                ('succeeded_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuance_batches', to='registry.congregation')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuance_batches_requested', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuance_batches', to='registry.congregationsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='last_issuance_batch',
            field=models.ForeignKey(blank=True, help_text='Most recent issuance batch this record was included in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='registry.issuancebatch'),
        ),
        migrations.AddIndex(
            model_name='issuancebatch',
            index=models.Index(fields=['session', '-created_at'], name='registry_is_session_f58a60_idx'),
        ),
        migrations.AddIndex(
            model_name='issuancebatch',
            index=models.Index(fields=['congregation', '-created_at'], name='registry_is_congreg_9a43b3_idx'),
        ),
        migrations.AddIndex(
            model_name='issuancebatch',
            index=models.Index(fields=['status'], name='registry_is_status_0dbd84_idx'),
        ),
    ]
