# Generated by Django 6.0.1 on 2026-06-24 13:18

from django.db import migrations, models


def backfill_names(apps, schema_editor):
    StudentRecord = apps.get_model('registry', 'StudentRecord')
    qs = StudentRecord.objects.select_related('faculty', 'department')
    for record in qs.iterator():
        changed = False
        if record.faculty_id and not record.faculty_name:
            record.faculty_name = record.faculty.name
            changed = True
        if record.department_id and not record.department_name:
            record.department_name = record.department.name
            changed = True
        if changed:
            record.save(update_fields=['faculty_name', 'department_name'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_issuancebatch_reference_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='department_name',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='faculty_name',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.RunPython(backfill_names, noop),
    ]
