# Generated by Django 6.0.1 on 2026-05-26 13:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_issuance_batch'),
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregation',
            name='sourced_from_congregation',
            field=models.ForeignKey(blank=True, help_text='Populated when this congregation was cloned from a previous year.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_congregations', to='registry.congregation'),
        ),
        migrations.CreateModel(
            name='CongregationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_congregation_templates', to=settings.AUTH_USER_MODEL)),
                ('sourced_from_congregation', models.ForeignKey(blank=True, help_text='Populated when this template was snapshotted from a congregation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_templates', to='registry.congregation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='congregation',
            name='sourced_from_template',
            field=models.ForeignKey(blank=True, help_text='Populated when this congregation was instantiated from a template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_congregations', to='registry.congregationtemplate'),
        ),
        migrations.CreateModel(
            name='CongregationTemplateSessionDef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_number', models.PositiveSmallIntegerField()),
                ('name_pattern', models.CharField(help_text="Used to derive the session's name when applied. Supports placeholders: {year}, {n} (session number).", max_length=255)),
                ('scope_type', models.CharField(choices=[('INSTITUTION', 'Institution-wide'), ('FACULTY', 'Faculty'), ('DEPARTMENT', 'Department')], max_length=20)),
                ('ceremony_day_offset', models.IntegerField(help_text='Days from congregation.ceremony_month (day 1) to ceremony_date.')),
                ('confirmation_window_days', models.PositiveSmallIntegerField(default=14, help_text='Days before ceremony_date that the confirmation deadline lands.')),
                ('issuance_instructions', models.TextField(blank=True)),
                ('default_certificate_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='templates.certificatetemplate')),
                ('default_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='registry.department')),
                ('default_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='registry.faculty')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_defs', to='registry.congregationtemplate')),
            ],
            options={
                'ordering': ['session_number'],
            },
        ),
        migrations.AddIndex(
            model_name='congregationtemplate',
            index=models.Index(fields=['is_active'], name='registry_co_is_acti_f0877d_idx'),
        ),
        migrations.AddConstraint(
            model_name='congregationtemplatesessiondef',
            constraint=models.UniqueConstraint(fields=('template', 'session_number'), name='registry_tmpl_unique_session_number'),
        ),
    ]
