# Generated by Django 6.0.1 on 2026-05-28 10:58

from django.db import migrations, models


def copy_ceremony_date(apps, schema_editor):
    CongregationSession = apps.get_model('registry', 'CongregationSession')
    for session in CongregationSession.objects.filter(ceremony_date__isnull=False):
        session.ceremony_start_date = session.ceremony_date
        session.ceremony_end_date = session.ceremony_date
        session.save(update_fields=['ceremony_start_date', 'ceremony_end_date'])


def reverse_copy(apps, schema_editor):
    CongregationSession = apps.get_model('registry', 'CongregationSession')
    for session in CongregationSession.objects.filter(ceremony_start_date__isnull=False):
        session.ceremony_date = session.ceremony_start_date
        session.save(update_fields=['ceremony_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_congregation_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='congregationsession',
            name='ceremony_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='congregationsession',
            name='ceremony_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='congregationsession',
            name='ceremony_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(copy_ceremony_date, reverse_copy),
    ]
