# Generated by Django 6.0.1 on 2026-07-02 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_studentrecord_department_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='dispute_proofs/')),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_attachments', to='registry.studentrecord')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
