# Generated by Django 6.0.1 on 2026-05-28 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_add_ceremony_dates'),
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congregationsession',
            name='ceremony_date',
        ),
        migrations.AlterField(
            model_name='congregationsession',
            name='ceremony_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='congregationsession',
            name='ceremony_start_date',
            field=models.DateField(),
        ),
        migrations.AddIndex(
            model_name='congregationsession',
            index=models.Index(fields=['ceremony_start_date'], name='registry_co_ceremon_9f6ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='congregationsession',
            index=models.Index(fields=['ceremony_end_date'], name='registry_co_ceremon_348540_idx'),
        ),
    ]
