# Generated by Django 6.0.1 on 2026-07-20 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_drop_full_name_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispute',
            new_name='registry_di_student_476a12_idx',
            old_name='registry_d_student__is_pe_idx',
        ),
        migrations.RenameIndex(
            model_name='dispute',
            new_name='registry_di_dispute_e9099e_idx',
            old_name='registry_d_dispute__is_pe_idx',
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='dispute_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='dispute_resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='dispute_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='dispute_resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='dispute_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issuancebatch',
            name='reference_name',
            field=models.CharField(blank=True, help_text='Human-friendly reference, auto-generated as BATCH-{year}-{NNNN}.', max_length=32, unique=True),
        ),
    ]
