# Generated by Django 6.0.1 on 2026-01-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('program', models.CharField(max_length=255)),
                ('graduation_date', models.DateField()),
                ('cohort', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
