# Generated by Django 6.0.1 on 2026-06-11 17:16

import core.permission_constants
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttemptTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_hash', models.CharField(help_text='SHA-256 hash of the email for privacy', max_length=64, unique=True)),
                ('attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('lockout_count_24h', models.IntegerField(default=0)),
                ('last_lockout_reset', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('ADMIN', 'Administrator'), ('STUDENT', 'Student'), ('EMPLOYER', 'Employer/Verifier')], max_length=20)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message to include in invitation email')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthorisationReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(help_text='Format: CERT-YYYY-STAFFID (e.g. CERT-2025-AB1234)', max_length=50, unique=True)),
                ('requester_name', models.CharField(help_text='Full legal name from letter', max_length=255)),
                ('requester_staff_id', models.CharField(help_text='Institutional staff ID', max_length=50)),
                ('authorising_head_name', models.CharField(max_length=255)),
                ('authorising_head_title', models.CharField(max_length=255)),
                ('authorising_head_department', models.CharField(max_length=255)),
                ('approval_date', models.DateField(help_text='Date the head in charge signed the letter')),
                ('intake_date', models.DateField(auto_now_add=True, help_text='Date Super Admin logged this')),
                ('scanned_letter', models.FileField(blank=True, help_text='Scanned copy of the approved letter', null=True, upload_to='authorisation_letters/')),
                ('purpose', models.CharField(choices=[('provision', 'Account Provisioning'), ('permission_change', 'Permission Change')], default='provision', help_text='What this authorisation letter is for', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('used', 'Used'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_account', models.ForeignKey(blank=True, help_text='Account this reference was used for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorisation_references', to=settings.AUTH_USER_MODEL)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_authorisations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdminDeactivationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('reason', models.TextField()),
                ('confirmation_token_hash', models.CharField(blank=True, max_length=64)),
                ('confirmation_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_deactivations', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_deactivations', to=settings.AUTH_USER_MODEL)),
                ('target_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deactivation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('ADMIN', 'Administrator'), ('STUDENT', 'Student'), ('EMPLOYER', 'Employer/Verifier')], default='ADMIN', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(blank=True, help_text='For Employers', max_length=255)),
                ('staff_id', models.CharField(blank=True, help_text='Institutional staff ID', max_length=50, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('account_type', models.CharField(choices=[('STAFF', 'Staff'), ('EXTERNAL_COLLABORATOR', 'External Collaborator')], default='STAFF', max_length=30)),
                ('access_duration', models.CharField(choices=[('permanent', 'Permanent'), ('time_limited', 'Time-limited')], default='permanent', max_length=20)),
                ('access_end_date', models.DateField(blank=True, help_text='Required if access_duration is time_limited', null=True)),
                ('permissions', models.JSONField(default=core.permission_constants.build_default_permissions, help_text='Granular permission flags — all default to false')),
                ('permission_history', models.JSONField(blank=True, default=list, help_text='Chronological list of permission change records')),
                ('is_legacy', models.BooleanField(default=False, help_text='True for accounts that existed before the provisioning system')),
                ('first_login_completed', models.BooleanField(default=False)),
                ('credential_token_hash', models.CharField(blank=True, max_length=64)),
                ('credential_expires_at', models.DateTimeField(blank=True, null=True)),
                ('credential_status', models.CharField(choices=[('none', 'None'), ('delivered', 'Credential Delivered'), ('completed', 'First Login Completed')], default='none', max_length=20)),
                ('letter_reference', models.ForeignKey(blank=True, help_text='Primary authorisation letter reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_profiles', to='core.authorisationreference')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='authorisationreference',
            index=models.Index(fields=['status', '-created_at'], name='core_author_status_11b588_idx'),
        ),
        migrations.AddIndex(
            model_name='authorisationreference',
            index=models.Index(fields=['purpose'], name='core_author_purpose_801cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='authorisationreference',
            index=models.Index(fields=['requester_staff_id'], name='core_author_request_e6a22f_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='core_userpr_role_ce56eb_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['staff_id'], name='core_userpr_staff_i_54ce02_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['credential_status'], name='core_userpr_credent_c70849_idx'),
        ),
    ]
