# Generated by Django 6.0.1 on 2026-02-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('ADMIN', 'Administrator'), ('STUDENT', 'Student'), ('EMPLOYER', 'Employer/Verifier')], default='STUDENT', max_length=20),
        ),
    ]
