# Generated by Django 6.0.1 on 2026-03-03 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_token_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admininvitation',
            name='token',
        ),
    ]
