# Generated by Django 6.0.1 on 2026-04-09 12:49

import core.permission_constants
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_admininvitation_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttemptTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_hash', models.CharField(help_text='SHA-256 hash of the email for privacy', max_length=64, unique=True)),
                ('attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('lockout_count_24h', models.IntegerField(default=0)),
                ('last_lockout_reset', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdminDeactivationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('reason', models.TextField()),
                ('confirmation_token_hash', models.CharField(blank=True, max_length=64)),
                ('confirmation_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_duration',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('time_limited', 'Time-limited')], default='permanent', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='access_end_date',
            field=models.DateField(blank=True, help_text='Required if access_duration is time_limited', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('EXTERNAL_COLLABORATOR', 'External Collaborator')], default='STAFF', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='credential_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='credential_status',
            field=models.CharField(choices=[('none', 'None'), ('delivered', 'Credential Delivered'), ('completed', 'First Login Completed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='credential_token_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_login_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='True for accounts that existed before the provisioning system'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permission_history',
            field=models.JSONField(blank=True, default=list, help_text='Chronological list of permission change records'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=models.JSONField(default=core.permission_constants.build_default_permissions, help_text='Granular permission flags — all default to false'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='staff_id',
            field=models.CharField(blank=True, help_text='Institutional staff ID', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('ADMIN', 'Administrator'), ('STUDENT', 'Student'), ('EMPLOYER', 'Employer/Verifier')], default='ADMIN', max_length=20),
        ),
        migrations.CreateModel(
            name='AuthorisationReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(help_text='Format: CERT-YYYY-STAFFID (e.g. CERT-2025-AB1234)', max_length=50, unique=True)),
                ('requester_name', models.CharField(help_text='Full legal name from letter', max_length=255)),
                ('requester_staff_id', models.CharField(help_text='Institutional staff ID', max_length=50)),
                ('authorising_head_name', models.CharField(max_length=255)),
                ('authorising_head_title', models.CharField(max_length=255)),
                ('authorising_head_department', models.CharField(max_length=255)),
                ('approval_date', models.DateField(help_text='Date the head in charge signed the letter')),
                ('intake_date', models.DateField(auto_now_add=True, help_text='Date Super Admin logged this')),
                ('scanned_letter', models.FileField(blank=True, help_text='Scanned copy of the approved letter', null=True, upload_to='authorisation_letters/')),
                ('provisioning_status', models.CharField(choices=[('pending', 'Pending'), ('provisioned', 'Provisioned'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_authorisations', to=settings.AUTH_USER_MODEL)),
                ('provisioned_account', models.OneToOneField(blank=True, help_text='Linked after account creation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorisation_reference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='letter_reference',
            field=models.ForeignKey(blank=True, help_text='Primary authorisation letter reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_profiles', to='core.authorisationreference'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='core_userpr_role_ce56eb_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['staff_id'], name='core_userpr_staff_i_54ce02_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['credential_status'], name='core_userpr_credent_c70849_idx'),
        ),
        migrations.AddField(
            model_name='superadmindeactivationrequest',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_deactivations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='superadmindeactivationrequest',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_deactivations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='superadmindeactivationrequest',
            name='target_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deactivation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='authorisationreference',
            index=models.Index(fields=['provisioning_status', '-created_at'], name='core_author_provisi_5f0152_idx'),
        ),
        migrations.AddIndex(
            model_name='authorisationreference',
            index=models.Index(fields=['requester_staff_id'], name='core_author_request_e6a22f_idx'),
        ),
    ]
