# Generated by Django 6.0.1 on 2026-02-22 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(max_length=255)),
                ('target', models.CharField(blank=True, default='', max_length=500)),
                ('details', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('warning', 'Warning')], default='success', max_length=20)),
                ('category', models.CharField(choices=[('admin', 'Admin Activity'), ('security', 'Security'), ('login', 'Login Attempt'), ('verification', 'Verification')], default='admin', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['category', '-timestamp'], name='analytics_a_categor_079531_idx'), models.Index(fields=['user', '-timestamp'], name='analytics_a_user_id_179d10_idx')],
            },
        ),
    ]
