# Generated by Django 6.0.1 on 2026-04-09 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='entry_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of this entry (content + previous_hash)', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(blank=True, default='', help_text='Structured event code, e.g. authorisation.logged, account.created', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='letter_reference',
            field=models.CharField(blank=True, default='', help_text='Authorisation letter reference number for traceability', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of the previous audit log entry', max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='category',
            field=models.CharField(choices=[('admin', 'Admin Activity'), ('security', 'Security'), ('login', 'Login Attempt'), ('verification', 'Verification'), ('provisioning', 'Account Provisioning'), ('permissions', 'Permission Changes'), ('credentials', 'Credential Events'), ('export', 'Data Export')], default='admin', max_length=20),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type', '-timestamp'], name='analytics_a_event_t_2bcd72_idx'),
        ),
    ]
