# Generated by Django 6.0.1 on 2026-01-16 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('degree_type', models.CharField(choices=[('BSC', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('BED', 'Bachelor of Education'), ('MSC', 'Master of Science'), ('MA', 'Master of Arts'), ('PHD', 'Doctor of Philosophy')], max_length=10)),
                ('honors', models.CharField(choices=[('FIRST', 'FIRST CLASS HONOURS'), ('SECOND_UPPER', 'SECOND CLASS HONOURS (Upper Division)'), ('SECOND_LOWER', 'SECOND CLASS HONOURS (Lower Division)'), ('THIRD', 'THIRD CLASS HONOURS'), ('PASS', 'PASS')], max_length=20)),
                ('program', models.CharField(max_length=255)),
                ('date_awarded', models.DateField()),
                ('university_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('vc_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('registrar_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('certificate_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-generated_date'],
            },
        ),
    ]
