# Generated by Django 6.0.1 on 2026-06-11 17:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('REVOKED', 'Revoked')], default='ISSUED', max_length=20)),
                ('student_name', models.CharField(max_length=255)),
                ('degree_type', models.CharField(choices=[('BSC', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('BED', 'Bachelor of Education'), ('MSC', 'Master of Science'), ('MA', 'Master of Arts'), ('PHD', 'Doctor of Philosophy'), ('BBA', 'Bachelor of Business Administration'), ('MPHIL', 'Master of Philosophy'), ('MED', 'Master of Education'), ('MBA', 'Master of Business Administration')], max_length=10)),
                ('honors', models.CharField(choices=[('FIRST', 'FIRST CLASS HONOURS'), ('SECOND_UPPER', 'SECOND CLASS HONOURS (Upper Division)'), ('SECOND_LOWER', 'SECOND CLASS HONOURS (Lower Division)'), ('THIRD', 'THIRD CLASS HONOURS'), ('PASS', 'PASS')], max_length=20)),
                ('program', models.CharField(max_length=255)),
                ('date_awarded', models.DateField()),
                ('university_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('vc_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('registrar_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('paper_size', models.CharField(blank=True, choices=[('A4', 'A4 (210 × 297 mm)'), ('LETTER', 'Letter (8.5 × 11 in)'), ('A3', 'A3 (297 × 420 mm)')], default='A4', max_length=10)),
                ('certificate_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='registry.studentrecord')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.certificatetemplate')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-generated_date'],
            },
        ),
    ]
