# Generated by Django 6.0.1 on 2026-06-19 10:42

import django.db.models.deletion
from django.db import migrations, models


def backfill_certificate_links(apps, schema_editor):
    """Set issuance_batch / issuance_run from the linked student_record."""
    Certificate = apps.get_model('certificates', 'Certificate')
    qs = Certificate.objects.filter(student_record__isnull=False).select_related(
        'student_record', 'student_record__last_issuance_run',
    )
    for cert in qs.iterator(chunk_size=500):
        record = cert.student_record
        cert.issuance_batch_id = record.batch_id
        cert.issuance_run_id = record.last_issuance_run_id
        cert.save(update_fields=['issuance_batch', 'issuance_run'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('registry', '0006_issuancebatch_reference_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='issuance_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='registry.issuancebatch'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuance_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='registry.issuancerun'),
        ),
        migrations.RunPython(backfill_certificate_links, noop_reverse),
    ]
