# Generated by Django 6.0.1 on 2026-01-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='degree_type',
            field=models.CharField(choices=[('BSC', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('BED', 'Bachelor of Education'), ('MSC', 'Master of Science'), ('MA', 'Master of Arts'), ('PHD', 'Doctor of Philosophy'), ('BBA', 'Bachelor of Business Administration'), ('MPHIL', 'Master of Philosophy'), ('MED', 'Master of Education'), ('MBA', 'Master of Business Administration')], max_length=10),
        ),
    ]
