# Generated by Django 6.0.1 on 2026-01-21 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificate_degree_type'),
        ('students', '0001_initial'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('REVOKED', 'Revoked')], default='ISSUED', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates.certificatetemplate'),
        ),
    ]
