# Generated by Django 6.0.1 on 2026-05-21 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='templates/backgrounds/')),
                ('canvas_width', models.IntegerField(default=800)),
                ('canvas_height', models.IntegerField(default=600)),
                ('metadata', models.JSONField(default=dict)),
                ('is_locked', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('official', 'Official'), ('draft', 'Draft'), ('internal', 'Internal')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
