# Generated by Django 6.0.1 on 2026-05-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='canvas_height',
            field=models.IntegerField(default=595),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='canvas_width',
            field=models.IntegerField(default=842),
        ),
    ]
