# Generated by Django 6.0.1 on 2026-06-11 17:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_mode', models.CharField(choices=[('realtime', 'Real-time'), ('daily_digest', 'Daily Digest'), ('critical_only', 'Critical Only')], default='realtime', max_length=20)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_target', models.CharField(blank=True, default='', help_text='Broadcast to all users with this role (e.g. SUPER_ADMIN).', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('notification_type', models.CharField(choices=[('certificate_issued', 'Certificate Issued'), ('bulk_issuance_complete', 'Bulk Issuance Complete'), ('certificate_revoked', 'Certificate Revoked'), ('certificate_reactivated', 'Certificate Reactivated'), ('blockchain_confirmed', 'Blockchain Confirmed'), ('blockchain_failed', 'Blockchain Failed'), ('template_updated', 'Template Updated'), ('template_locked', 'Template Locked'), ('student_activated', 'Student Activated'), ('admin_created', 'Admin Created'), ('verification_attempt', 'Verification Attempt'), ('suspicious_verification', 'Suspicious Verification'), ('reissue_request', 'Reissue Request'), ('employer_verification_saved', 'Employer Verification Saved'), ('config_changed', 'Configuration Changed'), ('new_device_login', 'New Device Login'), ('password_reset', 'Password Reset'), ('system', 'System')], default='system', max_length=50)),
                ('related_object_id', models.CharField(blank=True, default='', max_length=255)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('delivery_channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS')], default='in_app', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='Direct recipient. Null for role-based broadcasts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['role_target', '-created_at'], name='notificatio_role_ta_1b8ece_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx')],
            },
        ),
    ]
